name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: MamoonaRamzan
          outputs: dist/snake.svg
          snake_color: "#000000"          # snake color (black)
          background: "#000000"           # background (black)
          color_dots: "#39FF14 #FF3131 #FFD700 #00FFFF"  # colors for contributions

      - name: Push snake animation to GitHub
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
